# Generated by Django 2.2.6 on 2019-10-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField()),
                ('mission_name', models.CharField(max_length=100)),
                ('mission_id', models.IntegerField()),
                ('launch_year', models.DateField()),
                ('launch_date_local', models.DateTimeField()),
                ('is_tentative', models.BooleanField()),
            ],
        ),
    ]
